# Generated by Django 5.0.6 on 2024-07-24 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkliste', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='kriterien',
            name='kategorie',
        ),
        migrations.RemoveField(
            model_name='kriterien',
            name='projekt',
        ),
        migrations.RemoveField(
            model_name='projekt',
            name='user',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('gewichtung', models.PositiveIntegerField(choices=[(1, 'einfach'), (2, 'zweifach'), (3, 'dreifach')])),
                ('typ', models.CharField(max_length=100)),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkliste.category')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkliste.project')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkliste.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Kategorie',
        ),
        migrations.DeleteModel(
            name='Kriterien',
        ),
        migrations.DeleteModel(
            name='Projekt',
        ),
    ]
