# Generated by Django 5.0.6 on 2024-07-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkliste', '0002_category_remove_kriterien_kategorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterion',
            name='typ',
        ),
        migrations.AlterField(
            model_name='criterion',
            name='gewichtung',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'einfach'), (2, 'zweifach'), (3, 'dreifach')], null=True),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='rating',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
