# Generated by Django 5.0.6 on 2024-07-24 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkliste', '0003_remove_criterion_typ_alter_criterion_gewichtung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='subkategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkliste.subcategory'),
        ),
    ]
