# Generated by Django 5.0.6 on 2024-07-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkliste', '0004_criterion_subkategorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
