# Generated by Django 5.0.6 on 2024-07-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkliste', '0005_alter_category_name_alter_subcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
