# Generated by Django 5.0.6 on 2024-07-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkliste', '0006_alter_subcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='rating',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (0, 'Nicht relevant')], null=True),
        ),
    ]
